### ISSUE TITLE
Problem: there are no docs

### ISSUE THREAD

**Issue by sevein** [artefactual-labs/mets-reader-writer#30]
We should use the `docs/` project already available and we should wire it with Travis CI so it builds the page and pushes it into the gh-pages branch or readthedocs or similar.

**Comment by sevein** [comment]
We should also make sure that the PyPI homepage of the project shows useful information, e.g. https://pypi.python.org/pypi/Flask.

**Comment by ablwr** [comment]
:anguished:

**Comment by ross-spencer** [comment]
Closing as duplicate of https://github.com/archivematica/Issues/issues/609
